siteTitle="GovHackMT"
baseColor = "#244870"
linkPrefix = "/guia-desenvolvedor"
docPages = [
  "/docs/",
  "/docs/saude/",
  "/docs/contratos/",
  "/docs/educacao/",
  "/docs/seguranca-publica/",
  "/docs/censo/",
]
