siteTitle="GovHackMT"
baseColor = "#244870"
linkPrefix = "/"
docPages = [
  "/docs/",
  "/docs/saude/",
  "/docs/adm-publica/",
  "/docs/educacao/",
  "/docs/seguranca-publica/",
  "/docs/info-social/",
  "/docs/comercio/",
  #"/docs/contratos/",
  "/docs/outros/"
]
